### ISSUE TITLE
Cannot invoke "net.minecraft.class_239.method_17783()" because "hit" is null

### ISSUE THREAD

**Issue by cboxgo69** [DarkKronicle/KronHUD#103]
Getting the following unexpected error when trying to go to join a network server 

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_239.method_17783()" because "hit" is null
	at io.github.darkkronicle.kronhud.gui.hud.vanilla.CrosshairHud.getColor(CrosshairHud.java:144)
	at io.github.darkkronicle.kronhud.gui.hud.vanilla.CrosshairHud.render(CrosshairHud.java:66)
	at io.github.darkkronicle.kronhud.gui.HudManager.render(HudManager.java:79)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$zhl000$render(class_329.java:1496)
	at net.minecraft.class_329.method_1753(class_329.java:430)
	at net.minecraft.class_757.method_3192(class_757.java:1253)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**To Reproduce**
1. launch minecraft
2. go to multiplayer and try to join a server

**Expected behavior**
join without error

<img width="1440" alt="Screenshot 2022-11-23 at 5 27 39 AM" src="https://user-images.githubusercontent.com/89865647/203558558-6bf590c8-deee-4fb7-9f59-4640b76a8e9f.png">

**Comment by cboxgo69** [comment]
It might help to know that I rebooted and was able to launch single player mode, and the settings had crosshair enabled.  I don't recall ever enabling crosshair so it might be that it somehow got enabled.  At any rate, I did disable crosshair and I'm using the default crosshair.  I don't know if this will come up again but when I reported the error it had happened two days in a row.

I was also able to get into multiplayer servers after disabling crosshair.
