### ISSUE TITLE
[BUG] Game crashing while joining a server with resourcepack

### ISSUE THREAD

**Issue by itsMarkiS** [DarkKronicle/KronHUD#142]
**Game crashing while joining a server with resourcepack**

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_239.method_17783()" because "hit" is null
	at io.github.darkkronicle.kronhud.gui.hud.vanilla.CrosshairHud.getColor(CrosshairHud.java:148)
	at io.github.darkkronicle.kronhud.gui.hud.vanilla.CrosshairHud.render(CrosshairHud.java:70)
	at io.github.darkkronicle.kronhud.gui.HudManager.render(HudManager.java:79)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$bmo000$fabric-rendering-v1$render(class_329.java:6908)
	at net.minecraft.class_329.method_1753(class_329.java:374)
	at net.minecraft.class_757.method_3192(class_757.java:918)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by moehreag** [comment]
Can you please attach the full log? It contains valuable information for diagnosing this crash.
