### ISSUE TITLE
2.2.1 Crash

### ISSUE THREAD

**Issue by StillCreative** [DarkKronicle/KronHUD#88]
**Describe the bug**
Crash on a world load with 2.2.1

**To Reproduce**
1. Load Kronhud 2.2.1
2. Try to join any world
3. Crash on world load

**Expected behavior**
For it not to crash on world load

**Screenshots**
Not a screenshot but the error inside the log

[01:27:17] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "java.util.Map.size()" because "this.bossBars" is null
	at io.github.darkkronicle.kronhud.gui.hud.vanilla.BossBarHud.setBossBars(BossBarHud.java:48) ~[KronHUD-1.19.2-2.2.1.jar:?]
	at io.github.darkkronicle.kronhud.gui.hud.vanilla.BossBarHud.renderComponent(BossBarHud.java:62) ~[KronHUD-1.19.2-2.2.1.jar:?]
	at io.github.darkkronicle.kronhud.gui.entry.BoxHudEntry.render(BoxHudEntry.java:58) ~[KronHUD-1.19.2-2.2.1.jar:?]
	at io.github.darkkronicle.kronhud.gui.HudManager.render(HudManager.java:79) ~[KronHUD-1.19.2-2.2.1.jar:?]
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27) ~[fabric-rendering-v1-1.11.0+73145abb90-e222bbb82619b683.jar:?]
	at net.minecraft.class_329.handler$bgh002$render(class_329.java:3996) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:393) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:862) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]

**Additional context**
Not that it looked needed but I tested it on realms and singleplayer and it had the same result as expected

For the second time in a row I've forgotten to provide crash logs at first
[2022-10-14-2.log](https://github.com/DarkKronicle/KronHUD/files/9782823/2022-10-14-2.log)

**Comment by DarkKronicle** [comment]
Weird this is triggered, but should be an easy fix

**Comment by DarkKronicle** [comment]
This should be fixed next version
