### ISSUE TITLE
Random Crash while in game?

### ISSUE THREAD

**Issue by MarkinhosMLP** [DarkKronicle/KronHUD#97]
nothing different happened, it just crashed the game randomly

---- Minecraft Crash Report ----
// Don't do that.

Time: 2022-10-17 16:41:45
Description: Unexpected error

java.util.NoSuchElementException
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.client.util.math.MatrixStack.push(MatrixStack:66)
	at io.github.darkkronicle.kronhud.gui.entry.BoxHudEntry.render(BoxHudEntry.java:48)
	at io.github.darkkronicle.kronhud.gui.HudManager.render(HudManager.java:79)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.client.gui.hud.InGameHud.handler$cbg000$render(InGameHud:9496)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:430)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:1253)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1177)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$dbi000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:24522)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:795)
	at net.minecraft.client.main.Main.method_44604(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.class_4587.method_22903(class_4587.java:66)
	at io.github.darkkronicle.kronhud.gui.entry.BoxHudEntry.render(BoxHudEntry.java:48)
	at io.github.darkkronicle.kronhud.gui.HudManager.render(HudManager.java:79)
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27)
	at net.minecraft.class_329.handler$cbg000$render(class_329.java:9496)
	at net.minecraft.class_329.method_1753(class_329.java:430)

-- Affected level --
Details:
	All players: 1 total; [class_746['MarkinhosMLP'/890195, l='ClientLevel', x=-3444.88, y=78.00, z=-3902.42]]
	Chunk stats: 625, 313 F: 196 L: 0 U: 1
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,40), Section: (at 8,0,8 in 0,4,2; chunk contains blocks 0,-64,32 to 15,319,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 185450 game time, 68056 day time
	Server brand: Bidet <- Toiletpaper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:580)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$dbi000$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:24522)
	at net.minecraft.class_310.method_1514(class_310.java:795)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by DarkKronicle** [comment]
I've fixed this in the betas (you can find them in the Actions Tab -> betas -> latest -> summary -> artifacts. Download that and unpackage). This will be pushed to curseforge soon

**Comment by Grawl** [comment]
For easier access, here is the direct link to download a working version: [KronHUD-1.19.2-2.2.3.jar](https://github.com/DarkKronicle/KronHUD/suites/8802045812/artifacts/400261751)

Or you can go to workflow run 24 [Furry is a dingus](https://github.com/DarkKronicle/KronHUD/actions/runs/3262006180) and click on "Artifacts | 310 KB" on the page bottom.

**Comment by Fury-101** [comment]
I AM NOT A DINGUS!!!!!!!!!!!!!!!!!!!

**Comment by DarkKronicle** [comment]
Updating today
